### PR TITLE
*: rebase changes from v4.3.3-coreos

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by crawford** [comment]
/cc @mjg59 

I had to tweak 1b435189fb66e031edc4df509576448a96b4c3ff, changing the bit from 9 to 10.

**Comment by marineam** [comment]
Wouldn't this be "rebase" for "forward-port" changes ;-)

**Comment by crawford** [comment]
Indeed.

**Comment by mjg59** [comment]
@crawford That's fine - the bit isn't user-visible

**Pull request merged**
