### PR TITLE
overlayfs: use a minimal buffer in ovl_copy_xattr

### PR DESCRIPTION
**Pull request by vcaputo**
Rather than always allocating the high-order XATTR_SIZE_MAX buffer
which is costly and prone to failure, only allocate what is needed and
realloc if necessary.

Fixes https://github.com/coreos/bugs/issues/489

### CODE REVIEW

**Comment by hosh** [comment]
When do you guys think this will get merged in? I'm running into this issue on my deployment.

**Comment by mjg59** [comment]
lgtm

**Comment by hosh** [comment]
How would I get a kernel compiled with this onto my deployment? I've thought about kludging it, somehow turning off updates, and dropping it into the passive usr partition, then switching it over and rebooting.

Better yet, when is this patch going to make it into the Alpha channel? I'm frankly surprised that 835.1.0 got promoted to beta. Given that overlayfs stops working when it runs out of buffers, and on top of that,  Docker 1.8.3 compiled with Go 1.5 has problems pulling down images correctly, it doesn't seem like a good idea to promote it as a beta release.

**Comment by vcaputo** [comment]
@hosh http://alpha.release.core-os.net/amd64-usr/844.1.0/ should already contain this fix

**Comment by hosh** [comment]
@vcaputo awesome thanks!

**Pull request merged**
